### ISSUE TITLE
diff fails with IndexError

### ISSUE THREAD

**Issue by digininja** [tautology0/ayfabtu#2]
Getting this error:

```
$ ./git-grab  --url http://dvwa.test/pta/ --outdir /tmp/pta/ diff django_web_app/django_web_app/settings.py 0 1
Traceback (most recent call last):
  File "./git-grab", line 336, in <module>
    first=entry["ids"][vers2][0:2]
IndexError: list index out of range
```

Directory indexing isn't enabled on the server if that matters.

There are differences:

```
$ git log -p django_web_app/django_web_app/settings.py

commit bc616d230f921999b8e968011a98cf7087dfe104 (HEAD -> master, code-refactor)
Author: Steven R <steven@devel.evilcorp.com>
Date:   Sat Aug 15 03:08:52 2020 +0530

    Flag is removed now :)

diff --git a/django_web_app/django_web_app/settings.py b/django_web_app/django_web_app/settings.py
index 826395d..e571331 100644
--- a/django_web_app/django_web_app/settings.py
+++ b/django_web_app/django_web_app/settings.py
@@ -20,7 +20,7 @@ BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
 # See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/
 
 # SECURITY WARNING: keep the secret key used in production secret!
-SECRET_KEY = 'xxx'
+SECRET_KEY = '[ REDACTED ]'^M
```

Discover gives no response on the file either:

```
$ ./git-grab  --url http://dvwa.test/pta/ --outdir /tmp/pta/ discover django_web_app/django_web_app/settings.py 
```

I can send you the repo if you need it.

**Comment by tautology0** [comment]
Is this a new/dev version of DVWA? I couldn't replicate it from the docker version. I wonder whether I messed something up with paths on the URL.

**Comment by digininja** [comment]
It isn't DVWA, it is a repo for something else I just dropped on my DVWA
dev site.

I can send you the repo if you want.

**Comment by tautology0** [comment]
Yeah that would be the easiest way - I was going to DM you an email address, but your Twitter account doesn't accept DMs.

**Comment by digininja** [comment]
Don't worry, I know how to find you!

(I hope, if you've not had a mail through in next 10 mins, you'll be able
to DM me now)

**Comment by tautology0** [comment]
Got it! Thanks!

**Comment by tautology0** [comment]
Right, I've found the problem - I'd assumed that all branches were referenced in /.git/config. I was wrong - I can pull from HEAD and ORIG_HEAD too, I've just got to work out how to do it without messing up the code too much.

**Comment by digininja** [comment]
Great, well done

**Comment by tautology0** [comment]
Ah, it may be more complex - my logic around adding versions was a bit too simple. Will need to have a think.

**Comment by digininja** [comment]
I'm sure a man of your great intellect will be able to come up with a both
elegant and working solution in no time.

**Comment by tautology0** [comment]
It's amazing what a nights sleep and looking with new eyes on a problem will do: Fixed in https://github.com/tautology0/ayfabtu/commit/071575af31f46775e16b0f0807d7c0ca68f27486

The second problem was the way that git does trees (i.e. directories) - if a file in a directory is altered, the ID for the directory isn't  altered, this meant that it never recursed down the directory to find the file that had been altered. Rejiggling the if logic worked perfectly.

I updated the README file to make it explicit that you have to run discover first to find alternate versions. So the CTF should work with:

```
git-grab --url 127.0.0.1 discover
git-grab --url 127.0.0.1 diff django_web_app/django_web_app/settings.py 0 1 
git-grab --url 127.0.0.1 view django_web_app/django_web_app/settings.py --version 1
```

**Comment by digininja** [comment]
Thanks, passed it back to the team to test out in the lab.

Told you you could do it!
