### ISSUE TITLE
odd filename logged

### ISSUE THREAD

**Issue by digininja** [tautology0/ayfabtu#6]
Don't know if this is deliberate or not, but you create this oddly named file with the discover call:

```
./dvwa.test/pta/pta/.git/refs/heads:
total 12
drwxrwxr-x 2 robin robin 4096 Oct 20 21:53  .
drwxrwxr-x 3 robin robin 4096 Oct 20 21:53  ..
-rw-rw-r-- 1 robin robin   41 Oct 20 21:53 'master'$'\n'
```

Is it supposed to be named like that?

**Comment by digininja** [comment]
should have added, that is in the `.gitgrab` directory

**Comment by tautology0** [comment]
Oh, bum, I think I have may have got my pattern slightly wrong.

**Comment by tautology0** [comment]
Fixed in https://github.com/tautology0/ayfabtu/commit/9b2b7e31440f60d6af5da7342b3391d50266b34d

/me must remember to do an rstrip() after a read()
